# Needed for logging purposes. To be populated by DevOps - currently dummy
feFqdn: asdcFe.att.com

# catalog backend hostname
beHost: localhost

# catalog backend http port
beHttpPort: 8080

# catalog backend http context
beContext: /sdc2/rest/v1/catalog/upload/resources

# catalog backend protocol
beProtocol: http

# catalog backend ssl port
beSslPort: 8443

# threadpool size for handling requests
threadpoolSize: 50

# request processing timeout (seconds)
requestTimeout: 10

# Determines the health check read timeout when invoking health check towards the LB (or BE whatever is configured):
healthCheckSocketTimeoutInMs: 5000
healthCheckIntervalInSeconds: 5

onboarding:
  protocol: http
  host: localhost
  port: 8181
  healthCheckUri: "/onboarding/v1.0/healthcheck"

dcae:
  protocol: http
  host: localhost
  port: 8181
  healthCheckUri: "/dcae/healthCheck"

identificationHeaderFields:
   -
        - &HTTP_IV_USER HTTP_IV_USER
        - &iv-user iv-user
   -
        - &USER_ID USER_ID
        - &csp-userId csp-userId
   -
        - &HTTP_CSP_ATTUID HTTP_CSP_ATTUID
        - &csp-attuid csp-attuid
   -
        - &HTTP_CSP_WSTYPE HTTP_CSP_WSTYPE
        - &csp-wstype csp-wstype

optionalHeaderFields:
   -
        - &HTTP_CSP_FIRSTNAME HTTP_CSP_FIRSTNAME
        - &csp-firstname csp-firstname
   -
        - &HTTP_CSP_LASTNAME HTTP_CSP_LASTNAME
        - &csp-lastname csp-lastname
   -
        - &HTTP_IV_REMOTE_ADDRESS HTTP_IV_REMOTE_ADDRESS
        - &iv-remote-address iv-remote-address
   -
        - &HTTP_CSP_EMAIL HTTP_CSP_EMAIL
        - &csp-email csp-email

version: 1.0
released: 2012-11-30

# Connection parameters
connection:
    url: jdbc:mysql://localhost:3306/db
    poolSize: 17

# Protocols
protocols:
   - http
   - https


systemMonitoring:
    enabled: false
    isProxy: true
    probeIntervalInSeconds: 15

kibanaHost: localhost
kibanaPort: 5601
kibanaProtocol: http
