designersList:
   - designerId: DCAE
     designerHost: localhost
     designerPort: 8080
     designerPath: "/dcae"
     designerStateUrl: "dcae"
     designerProtocol: http
     designerDisplayOptions:
        tab:
            displayName: "monitor"
            validResourceTypes: ["VF", "SERVICE"]
        top:
            displayName: "DCAE"
   - designerId: WORKFLOW
     designerHost: localhost
     designerPort: 9527
     designerPath: "/"
     designerStateUrl: "workflowDesigner"
     designerProtocol: http
     designerDisplayOptions:
        top:
            displayName: "Workflow Designer"